### ISSUE TITLE
Deploy Rabble Rouser to AWS

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#15]
Probably on AWS. Has to be secure, and automated.

_From @akjones on April 11, 2016 8:19_

_Copied from original issue: rabblerouser/rabblerouser-core-fork#14_

**Comment by akjones** [comment]
Docker yes (because dependencies are a pain, and deployment become trivial and fast). Kubernetes maybe. If AWS, RDS yes (because don't manage the DB if you don't have to).

If AWS, cloudformation (or terraform) to spin up the infra, then kubectl to lay down the apps.

Kubernetes seems like a good fit since it was built to run containers, has lots of different levels of abstractions (pod, deployment, service) and can be self-healing (which, if folks are running their own instances, this'll help with basic day-to-day maintenance).

Separate containers for front and back.

HTTPS everywhere (as in each app should have https).

**Comment by akjones** [comment]
For mvp, we'll keep going with ansible. RDS database. Nginx serving static content, terminating https, and proxying to the backend.

**Comment by tomsulston** [comment]
Broken provisioning AWS server, RDS instance, SSL certs, and deploying into separate tasks. Any more?
