### ISSUE TITLE
Make all the back-end code pass eslint

### ISSUE THREAD

**Issue by camjackson** [rabblerouser/core#21]
_From @camjackson on April 18, 2016 13:40_

_Copied from original issue: rabblerouser/rabblerouser-core-fork#20_

**Comment by camjackson** [comment]
Reminder: Once the backend code all passes the linter, the `ci` task in `backend/package.json` should have the linter task added to it, rather than just running the tests.

**Comment by elimydlarz** [comment]
So, it doesn't _all_ pass because of things like 'use strict' (which somebody suggested we still need), line length violations caused by template literals and functions that write to their params. Otherwise we're all done. I'm not sure if addressing those issues should be part of this card or not - thoughts?

**Comment by camjackson** [comment]
Summarising the slack conversation here for posterity: We'll add some exceptions for now to get the linter passing ASAP, and document the remaining things we want to do. Some of them may go in #26, others might be a new issue.

**Comment by elimydlarz** [comment]
It's only just now occurred to me that I have no included the specs in my lint pass. How do people feel about doing that? Personally I'd like to skip it _for now_.
