### ISSUE TITLE
i can customise the app so that my organisation's name appears instead of the generic name

### ISSUE THREAD

**Issue by akjones** [rabblerouser/core#32]
As a Rabble Rouser administrator, when I add a key with name "organisation_name" and value "Awesome Org" to the config file, and I reload the app, then I should see references to "Awesome Org" instead of Rabble Rouser (or the Lab, or any other organisation).

This will enable us to whitelabel the site, and deploy it for any organisation.

**Comment by pameck** [comment]
I have an idea for this but part of  it seems dodgy, please provide feedback!

First, to have a "customise/custom/whatever" folder where the user could change not only the skins but the organisation name, and any UI customisation that we might come up with in the future. For the organisation name, have a property `organisation_name` in `custom/main.json`

We have the same `organisation_name` in `scr/config/string.js` defaulted to Rabble Rouser. 

The organisation name appears as the title the sign up page, admin and organiser dashboard.
This is set in static html, in `<title>`:
1. `/frontend/public/admin.html`
2. `/frontend/public/dashboard.html`
3. `/frontend/public/index.html`

My idea would be to add a JS script, besides the bundle, to dynamically set the title based on `custom/main.json` and ``scr/config/string.js` (which I would have to import as well)

What'd y'all thing?

**Comment by camjackson** [comment]
@pameck I'm actually going to explore building a basic UI to do this, and storing key/val pairs in the database. I think it might actually be pretty easy to implement, and it saves us from doing tricky stuff with files and build processes etc. Better UX too of course!

If it turns out to be a huge job though, then I won't spend too much time on it, and I'll come back to a more config-file-based solution.

**Comment by camjackson** [comment]
OK, how's this for a simple temporary solution:
- There's an entry in the `config` object in the frontend package.json
- That's available to be used anywhere in the frontend app as an environment variable: `process.env.ORG_NAME`

This is a really easy change to make. The only tricky bit is persisting the config entry when upgrading/deploying the app. I haven't figured that bit out yet, and my brain is currently in a liquid state, so I'm open to ideas.

**Comment by camjackson** [comment]
After chatting with @yearofthedan, we came up with a slightly better solution.

We'll still use an environment variable to provide the org name, but instead of needing to commit it into the repo somewhere (and then needing to keep that change when upgrading the app), it can just be provided as a regular environment variable at build time.

So instead of `npm run build`, you'd do something like `ORG_NAME='Hack for Privacy' npm run build`. Then we can hardcode that in the build pipeline, rather than needing to put instance-specific stuff into the codebase.

**Comment by camjackson** [comment]
Notes for testing:
- I've added [instructions](https://github.com/rabblerouser/rabblerouser-core#customising-the-app-for-your-organisation) to the README to show how to customise the organisation name and skin
- You can test this out in staging by changing the environment variables from the [heroku dashbord](https://dashboard.heroku.com/apps/rabblerouser-core/settings), and rebuilding**

*\* It needs a rebuild, not just a restart, because the config gets baked into the frontend at compile time. Unfortunately it [looks like](https://stackoverflow.com/questions/9713183/recompile-heroku-slug-without-push-or-config-change) Heroku doesn't let you trigger a rebuild manually. It only happens when you push a commit :(
